### ISSUE TITLE
Sett opp zoom-roulette

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/Slack#1]
Vi introduserer random møter mellom to og to kolleger, og trenger en møteliste. Hvem skal snakke med hvem rett og slett.

Versjon 1 må sette opp listen over hvem som skal ha møter. Listen skal være helt random, som vil si at noen kan få samme møte-partner to ganger på rad, men over tid vil statistikken balansere ut dette.

Steg 1: lag systemet som setter opp møtelisten
Steg 2 (hvis tid): lag en slack-integration hvor en bruker kan velge hvem som skal være med i denne runden

**Steg 1:**
Opprett et endpoint i endpoint-mappen, som sender en møte-agenda til en slack-kanal

**Comment by mariusmandal** [comment]
Er vi ferdig med denne @kimduo ? :)

**Comment by kimduo** [comment]
Den er ferdig 👍  @mariusmandal
